/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chat {
  'id' : ChatId,
  'participant1' : UserId,
  'participant2' : UserId,
  'messages' : Array<ChatMessage>,
}
export type ChatId = bigint;
export interface ChatMessage {
  'content' : string,
  'sender' : UserId,
  'timestamp' : bigint,
}
export type City = string;
export type ExternalBlob = Uint8Array;
export type Gender = { 'female' : null } |
  { 'male' : null };
export interface Image {
  'blob' : ExternalBlob,
  'name' : string,
  'fileType' : string,
}
export interface Profile {
  'bio' : string,
  'owner' : UserId,
  'interests' : Array<string>,
  'city' : City,
  'name' : string,
  'profilePhoto' : [] | [Image],
  'connectWith' : [] | [Gender],
  'gender' : [] | [Gender],
}
export interface Subscription {
  'startTime' : bigint,
  'plan' : SubscriptionPlan,
  'expiryTime' : [] | [bigint],
}
export type SubscriptionPlan = { 'plan98' : null } |
  { 'none' : null } |
  { 'plan199' : null } |
  { 'plan399' : null };
export type UserId = Principal;
export interface UserProfileUpdate {
  'bio' : string,
  'interests' : Array<string>,
  'city' : City,
  'name' : string,
  'profilePhoto' : [] | [Image],
  'connectWith' : Gender,
  'gender' : Gender,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activatePlan' : ActorMethod<[SubscriptionPlan], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[UserId], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfileUpdate], undefined>,
  'getAllSubscriptions' : ActorMethod<[], Array<[UserId, Subscription]>>,
  'getAllUserProfiles' : ActorMethod<[], Array<Profile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getOwnProfile' : ActorMethod<[], Profile>,
  'getPlan' : ActorMethod<[], SubscriptionPlan>,
  'getProfilesByCity' : ActorMethod<[City], Array<Profile>>,
  'getReportedUsers' : ActorMethod<[], Array<[UserId, bigint]>>,
  'getUserChats' : ActorMethod<[], Array<Chat>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isBlockedBy' : ActorMethod<[UserId, UserId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reportUser' : ActorMethod<[UserId], undefined>,
  'resetUserChatCount' : ActorMethod<[UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileUpdate], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], undefined>,
  'startChat' : ActorMethod<[UserId], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];