/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SubscriptionPlan = IDL.Variant({
  'plan98' : IDL.Null,
  'none' : IDL.Null,
  'plan199' : IDL.Null,
  'plan399' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const City = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Image = IDL.Record({
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'fileType' : IDL.Text,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const UserProfileUpdate = IDL.Record({
  'bio' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'city' : City,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(Image),
  'connectWith' : Gender,
  'gender' : Gender,
});
export const Subscription = IDL.Record({
  'startTime' : IDL.Int,
  'plan' : SubscriptionPlan,
  'expiryTime' : IDL.Opt(IDL.Int),
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'owner' : UserId,
  'interests' : IDL.Vec(IDL.Text),
  'city' : City,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(Image),
  'connectWith' : IDL.Opt(Gender),
  'gender' : IDL.Opt(Gender),
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : UserId,
  'timestamp' : IDL.Int,
});
export const ChatId = IDL.Nat;
export const Chat = IDL.Record({
  'id' : ChatId,
  'participant1' : UserId,
  'participant2' : UserId,
  'messages' : IDL.Vec(ChatMessage),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activatePlan' : IDL.Func([SubscriptionPlan], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([UserId], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfileUpdate], [], []),
  'getAllSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserId, Subscription))],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getOwnProfile' : IDL.Func([], [Profile], ['query']),
  'getPlan' : IDL.Func([], [SubscriptionPlan], ['query']),
  'getProfilesByCity' : IDL.Func([City], [IDL.Vec(Profile)], ['query']),
  'getReportedUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserId, IDL.Nat))],
      ['query'],
    ),
  'getUserChats' : IDL.Func([], [IDL.Vec(Chat)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isBlockedBy' : IDL.Func([UserId, UserId], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reportUser' : IDL.Func([UserId], [], []),
  'resetUserChatCount' : IDL.Func([UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileUpdate], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'startChat' : IDL.Func([UserId], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SubscriptionPlan = IDL.Variant({
    'plan98' : IDL.Null,
    'none' : IDL.Null,
    'plan199' : IDL.Null,
    'plan399' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const City = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Image = IDL.Record({
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'fileType' : IDL.Text,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const UserProfileUpdate = IDL.Record({
    'bio' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'city' : City,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(Image),
    'connectWith' : Gender,
    'gender' : Gender,
  });
  const Subscription = IDL.Record({
    'startTime' : IDL.Int,
    'plan' : SubscriptionPlan,
    'expiryTime' : IDL.Opt(IDL.Int),
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'owner' : UserId,
    'interests' : IDL.Vec(IDL.Text),
    'city' : City,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(Image),
    'connectWith' : IDL.Opt(Gender),
    'gender' : IDL.Opt(Gender),
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : UserId,
    'timestamp' : IDL.Int,
  });
  const ChatId = IDL.Nat;
  const Chat = IDL.Record({
    'id' : ChatId,
    'participant1' : UserId,
    'participant2' : UserId,
    'messages' : IDL.Vec(ChatMessage),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activatePlan' : IDL.Func([SubscriptionPlan], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([UserId], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfileUpdate], [], []),
    'getAllSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserId, Subscription))],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getOwnProfile' : IDL.Func([], [Profile], ['query']),
    'getPlan' : IDL.Func([], [SubscriptionPlan], ['query']),
    'getProfilesByCity' : IDL.Func([City], [IDL.Vec(Profile)], ['query']),
    'getReportedUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserId, IDL.Nat))],
        ['query'],
      ),
    'getUserChats' : IDL.Func([], [IDL.Vec(Chat)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isBlockedBy' : IDL.Func([UserId, UserId], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reportUser' : IDL.Func([UserId], [], []),
    'resetUserChatCount' : IDL.Func([UserId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileUpdate], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'startChat' : IDL.Func([UserId], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };